[2024-02-21 04:59:46,828] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: csv_transformation_and_class_creation.transform_csv_task scheduled__2024-02-20T00:00:00+00:00 [queued]>
[2024-02-21 04:59:46,837] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: csv_transformation_and_class_creation.transform_csv_task scheduled__2024-02-20T00:00:00+00:00 [queued]>
[2024-02-21 04:59:46,837] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-02-21 04:59:46,838] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2024-02-21 04:59:46,838] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-02-21 04:59:46,849] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): transform_csv_task> on 2024-02-20 00:00:00+00:00
[2024-02-21 04:59:46,854] {standard_task_runner.py:52} INFO - Started process 563 to run task
[2024-02-21 04:59:46,857] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'csv_transformation_and_class_creation', 'transform_csv_task', 'scheduled__2024-02-20T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmpa60jzwmg', '--error-file', '/tmp/tmpxnsxp54d']
[2024-02-21 04:59:46,857] {standard_task_runner.py:80} INFO - Job 7: Subtask transform_csv_task
[2024-02-21 04:59:46,900] {task_command.py:369} INFO - Running <TaskInstance: csv_transformation_and_class_creation.transform_csv_task scheduled__2024-02-20T00:00:00+00:00 [running]> on host 7f99983bc7dc
[2024-02-21 04:59:46,959] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=csv_transformation_and_class_creation
AIRFLOW_CTX_TASK_ID=transform_csv_task
AIRFLOW_CTX_EXECUTION_DATE=2024-02-20T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-02-20T00:00:00+00:00
[2024-02-21 04:59:47,250] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dags.py", line 33, in transform_csv
    input_path = kwargs['params']['input_path']
KeyError: 'input_path'
[2024-02-21 04:59:47,261] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=csv_transformation_and_class_creation, task_id=transform_csv_task, execution_date=20240220T000000, start_date=20240221T045946, end_date=20240221T045947
[2024-02-21 04:59:47,271] {standard_task_runner.py:97} ERROR - Failed to execute job 7 for task transform_csv_task ('input_path'; 563)
[2024-02-21 04:59:47,288] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-02-21 04:59:47,322] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
