[2024-02-21 04:55:05,615] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: csv_transformation_and_class_creation.transform_csv_task manual__2024-02-21T04:55:04.807128+00:00 [queued]>
[2024-02-21 04:55:05,628] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: csv_transformation_and_class_creation.transform_csv_task manual__2024-02-21T04:55:04.807128+00:00 [queued]>
[2024-02-21 04:55:05,629] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-02-21 04:55:05,629] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-02-21 04:55:05,629] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-02-21 04:55:05,641] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): transform_csv_task> on 2024-02-21 04:55:04.807128+00:00
[2024-02-21 04:55:05,646] {standard_task_runner.py:52} INFO - Started process 347 to run task
[2024-02-21 04:55:05,649] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'csv_transformation_and_class_creation', 'transform_csv_task', 'manual__2024-02-21T04:55:04.807128+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmpp7zu9wt7', '--error-file', '/tmp/tmp56plo__z']
[2024-02-21 04:55:05,650] {standard_task_runner.py:80} INFO - Job 5: Subtask transform_csv_task
[2024-02-21 04:55:05,686] {task_command.py:369} INFO - Running <TaskInstance: csv_transformation_and_class_creation.transform_csv_task manual__2024-02-21T04:55:04.807128+00:00 [running]> on host 7f99983bc7dc
[2024-02-21 04:55:05,768] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=csv_transformation_and_class_creation
AIRFLOW_CTX_TASK_ID=transform_csv_task
AIRFLOW_CTX_EXECUTION_DATE=2024-02-21T04:55:04.807128+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-02-21T04:55:04.807128+00:00
[2024-02-21 04:55:05,960] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dags.py", line 33, in transform_csv
    input_path = kwargs['params']['input_path']
KeyError: 'input_path'
[2024-02-21 04:55:05,968] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=csv_transformation_and_class_creation, task_id=transform_csv_task, execution_date=20240221T045504, start_date=20240221T045505, end_date=20240221T045505
[2024-02-21 04:55:05,975] {standard_task_runner.py:97} ERROR - Failed to execute job 5 for task transform_csv_task ('input_path'; 347)
[2024-02-21 04:55:06,000] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-02-21 04:55:06,028] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
