[2024-02-21 05:10:40,899] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: csv_transformation_and_class_creation.create_class_task manual__2024-02-21T05:10:39.272064+00:00 [queued]>
[2024-02-21 05:10:40,907] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: csv_transformation_and_class_creation.create_class_task manual__2024-02-21T05:10:39.272064+00:00 [queued]>
[2024-02-21 05:10:40,907] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-02-21 05:10:40,907] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-02-21 05:10:40,908] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-02-21 05:10:40,917] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): create_class_task> on 2024-02-21 05:10:39.272064+00:00
[2024-02-21 05:10:40,920] {standard_task_runner.py:52} INFO - Started process 1101 to run task
[2024-02-21 05:10:40,922] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'csv_transformation_and_class_creation', 'create_class_task', 'manual__2024-02-21T05:10:39.272064+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmpi9drl6m3', '--error-file', '/tmp/tmph07eq0dp']
[2024-02-21 05:10:40,923] {standard_task_runner.py:80} INFO - Job 16: Subtask create_class_task
[2024-02-21 05:10:40,958] {task_command.py:369} INFO - Running <TaskInstance: csv_transformation_and_class_creation.create_class_task manual__2024-02-21T05:10:39.272064+00:00 [running]> on host 7f99983bc7dc
[2024-02-21 05:10:41,015] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=csv_transformation_and_class_creation
AIRFLOW_CTX_TASK_ID=create_class_task
AIRFLOW_CTX_EXECUTION_DATE=2024-02-21T05:10:39.272064+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-02-21T05:10:39.272064+00:00
[2024-02-21 05:10:41,016] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-02-21 05:10:41,017] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python models.py']
[2024-02-21 05:10:41,026] {subprocess.py:85} INFO - Output:
[2024-02-21 05:10:41,100] {subprocess.py:92} INFO - python: can't open file 'models.py': [Errno 2] No such file or directory
[2024-02-21 05:10:41,103] {subprocess.py:96} INFO - Command exited with return code 2
[2024-02-21 05:10:41,116] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-02-21 05:10:41,119] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=csv_transformation_and_class_creation, task_id=create_class_task, execution_date=20240221T051039, start_date=20240221T051040, end_date=20240221T051041
[2024-02-21 05:10:41,145] {standard_task_runner.py:97} ERROR - Failed to execute job 16 for task create_class_task (Bash command failed. The command returned a non-zero exit code 2.; 1101)
[2024-02-21 05:10:41,186] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-02-21 05:10:41,211] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
