[2024-02-21 05:44:49,195] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: csv_transformation_and_class_creation.create_class_task manual__2024-02-21T05:39:45.183338+00:00 [queued]>
[2024-02-21 05:44:49,210] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: csv_transformation_and_class_creation.create_class_task manual__2024-02-21T05:39:45.183338+00:00 [queued]>
[2024-02-21 05:44:49,211] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-02-21 05:44:49,211] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2024-02-21 05:44:49,212] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-02-21 05:44:49,228] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): create_class_task> on 2024-02-21 05:39:45.183338+00:00
[2024-02-21 05:44:49,233] {standard_task_runner.py:52} INFO - Started process 2735 to run task
[2024-02-21 05:44:49,238] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'csv_transformation_and_class_creation', 'create_class_task', 'manual__2024-02-21T05:39:45.183338+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmpe5spp4pw', '--error-file', '/tmp/tmp6a23qdpk']
[2024-02-21 05:44:49,239] {standard_task_runner.py:80} INFO - Job 35: Subtask create_class_task
[2024-02-21 05:44:49,298] {task_command.py:369} INFO - Running <TaskInstance: csv_transformation_and_class_creation.create_class_task manual__2024-02-21T05:39:45.183338+00:00 [running]> on host 7f99983bc7dc
[2024-02-21 05:44:49,450] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=csv_transformation_and_class_creation
AIRFLOW_CTX_TASK_ID=create_class_task
AIRFLOW_CTX_EXECUTION_DATE=2024-02-21T05:39:45.183338+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-02-21T05:39:45.183338+00:00
[2024-02-21 05:44:49,457] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-02-21 05:44:49,458] {subprocess.py:74} INFO - Running command: ['bash', '-c', '/Library/Frameworks/Python.framework/Versions/3.10/bin/pytest /opt/***/dags/tests']
[2024-02-21 05:44:49,470] {subprocess.py:85} INFO - Output:
[2024-02-21 05:44:49,477] {subprocess.py:92} INFO - bash: line 1: /Library/Frameworks/Python.framework/Versions/3.10/bin/pytest: No such file or directory
[2024-02-21 05:44:49,478] {subprocess.py:96} INFO - Command exited with return code 127
[2024-02-21 05:44:49,530] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-02-21 05:44:49,538] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=csv_transformation_and_class_creation, task_id=create_class_task, execution_date=20240221T053945, start_date=20240221T054449, end_date=20240221T054449
[2024-02-21 05:44:49,562] {standard_task_runner.py:97} ERROR - Failed to execute job 35 for task create_class_task (Bash command failed. The command returned a non-zero exit code 127.; 2735)
[2024-02-21 05:44:49,584] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-02-21 05:44:49,630] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
