[2024-02-21 05:20:02,783] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: csv_transformation_and_class_creation.create_class_task manual__2024-02-21T05:14:59.925469+00:00 [queued]>
[2024-02-21 05:20:02,791] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: csv_transformation_and_class_creation.create_class_task manual__2024-02-21T05:14:59.925469+00:00 [queued]>
[2024-02-21 05:20:02,791] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-02-21 05:20:02,792] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2024-02-21 05:20:02,792] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-02-21 05:20:02,802] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): create_class_task> on 2024-02-21 05:14:59.925469+00:00
[2024-02-21 05:20:02,806] {standard_task_runner.py:52} INFO - Started process 1541 to run task
[2024-02-21 05:20:02,809] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'csv_transformation_and_class_creation', 'create_class_task', 'manual__2024-02-21T05:14:59.925469+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmpggv46gna', '--error-file', '/tmp/tmpulukeahv']
[2024-02-21 05:20:02,810] {standard_task_runner.py:80} INFO - Job 20: Subtask create_class_task
[2024-02-21 05:20:02,846] {task_command.py:369} INFO - Running <TaskInstance: csv_transformation_and_class_creation.create_class_task manual__2024-02-21T05:14:59.925469+00:00 [running]> on host 7f99983bc7dc
[2024-02-21 05:20:02,898] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=csv_transformation_and_class_creation
AIRFLOW_CTX_TASK_ID=create_class_task
AIRFLOW_CTX_EXECUTION_DATE=2024-02-21T05:14:59.925469+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-02-21T05:14:59.925469+00:00
[2024-02-21 05:20:02,899] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-02-21 05:20:02,901] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python /Users/maheshsai/Documents/BD/ass3/part1/tests/test_models.py']
[2024-02-21 05:20:02,907] {subprocess.py:85} INFO - Output:
[2024-02-21 05:20:02,984] {subprocess.py:92} INFO - python: can't open file '/Users/maheshsai/Documents/BD/ass3/part1/tests/test_models.py': [Errno 2] No such file or directory
[2024-02-21 05:20:02,986] {subprocess.py:96} INFO - Command exited with return code 2
[2024-02-21 05:20:02,998] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-02-21 05:20:03,001] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=csv_transformation_and_class_creation, task_id=create_class_task, execution_date=20240221T051459, start_date=20240221T052002, end_date=20240221T052003
[2024-02-21 05:20:03,009] {standard_task_runner.py:97} ERROR - Failed to execute job 20 for task create_class_task (Bash command failed. The command returned a non-zero exit code 2.; 1541)
[2024-02-21 05:20:03,030] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-02-21 05:20:03,054] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
