[2024-02-21 05:37:49,513] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: csv_transformation_and_class_creation.create_class_task manual__2024-02-21T05:37:47.582204+00:00 [queued]>
[2024-02-21 05:37:49,520] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: csv_transformation_and_class_creation.create_class_task manual__2024-02-21T05:37:47.582204+00:00 [queued]>
[2024-02-21 05:37:49,521] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-02-21 05:37:49,521] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-02-21 05:37:49,521] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-02-21 05:37:49,530] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): create_class_task> on 2024-02-21 05:37:47.582204+00:00
[2024-02-21 05:37:49,533] {standard_task_runner.py:52} INFO - Started process 2407 to run task
[2024-02-21 05:37:49,536] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'csv_transformation_and_class_creation', 'create_class_task', 'manual__2024-02-21T05:37:47.582204+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmpp4pmpiwp', '--error-file', '/tmp/tmp97nf21vd']
[2024-02-21 05:37:49,536] {standard_task_runner.py:80} INFO - Job 31: Subtask create_class_task
[2024-02-21 05:37:49,572] {task_command.py:369} INFO - Running <TaskInstance: csv_transformation_and_class_creation.create_class_task manual__2024-02-21T05:37:47.582204+00:00 [running]> on host 7f99983bc7dc
[2024-02-21 05:37:49,621] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=csv_transformation_and_class_creation
AIRFLOW_CTX_TASK_ID=create_class_task
AIRFLOW_CTX_EXECUTION_DATE=2024-02-21T05:37:47.582204+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-02-21T05:37:47.582204+00:00
[2024-02-21 05:37:49,622] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-02-21 05:37:49,623] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'pytest /opt/***/dags/tests']
[2024-02-21 05:37:49,630] {subprocess.py:85} INFO - Output:
[2024-02-21 05:37:49,631] {subprocess.py:92} INFO - bash: line 1: pytest: command not found
[2024-02-21 05:37:49,632] {subprocess.py:96} INFO - Command exited with return code 127
[2024-02-21 05:37:49,643] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-02-21 05:37:49,646] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=csv_transformation_and_class_creation, task_id=create_class_task, execution_date=20240221T053747, start_date=20240221T053749, end_date=20240221T053749
[2024-02-21 05:37:49,654] {standard_task_runner.py:97} ERROR - Failed to execute job 31 for task create_class_task (Bash command failed. The command returned a non-zero exit code 127.; 2407)
[2024-02-21 05:37:49,676] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-02-21 05:37:49,698] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
